# Generated by Django 6.0.2 on 2026-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='Description (Persian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Persian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='Description (Persian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_irr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Discount Price (IRR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Persian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_irr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Price (IRR)'),
        ),
    ]
