# Generated by Django 6.0.2 on 2026-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_description_fa_category_name_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_irr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Cost Price (IRR)'),
        ),
    ]
